"""empty message

Revision ID: 8c3dfa6b8010
Revises: 32fec55ece1a
Create Date: 2023-08-15 02:44:29.807152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3dfa6b8010'
down_revision = '32fec55ece1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_hp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_hp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('current_hp')
        batch_op.drop_column('max_hp')
        batch_op.drop_column('experience')
        batch_op.drop_column('level')

    # ### end Alembic commands ###