"""empty message

Revision ID: 537e6ef32997
Revises: 8c3dfa6b8010
Create Date: 2023-08-15 04:03:54.459961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537e6ef32997'
down_revision = '8c3dfa6b8010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ramen', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ramen')

    # ### end Alembic commands ###